---
# This tasks is designed to be imported and ran with papertrail_new_watch_files var set 
# to append values to papertrail_watch_files if they have already been defined. 
# This allows the role to run and install all watch files at once or only per role.
- name: add logs to paper_trail_watch_files var
  set_fact:
    papertrail_watch_files: "{{  papertrail_watch_files + papertrail_new_watch_files }}"
  changes_when: True
  notify: rsyslog
  tags: 
    - papertrail
    - config
